- name: Commit and Push
  env:
    TOKEN: ${{ secrets.GH_TOKEN }}
  run: |
    git config --global user.name "YashwanthBot"
    git config --global user.email "yashwanthv7@users.noreply.github.com"
    git add .
    git commit -m "Auto-sync Medium writeups" || echo "No changes to commit"
    git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
