name: Medium Sync

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

jobs:
  sync_medium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Debug Info
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Current branch:"
          git branch
          echo "Repository:"
          echo ${{ github.repository }}
          echo "Token present: ${TOKEN:+Yes}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install feedparser markdownify

      - name: Run Medium to MD script
        run: python scripts/medium_to_md.py

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "YashwanthBot"
          git config --global user.email "yashwanthv7@users.noreply.github.com"
          git add .
          git commit -m "Auto-sync Medium writeups" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
